Implment base Story Translation page
uwblueprint/planet-read pull request #154
Opened 2021-11-08 15:36 UTC by gaoxk

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Implement-dumb-admin-story-translation-page-731159c382c5406ea3ea3fb619465d16)

## Implementation description

- implement side bar 
  - backend needs to be modified to return the translator/reviewer names and the total number of lines
- implemented form 
  - making a dumb non functioning form for now
- implemented bottom footer  
  - buttons are non functioning
- using default nav for now   

tldr, only functioning thing is the delete button

## Steps to test

1. login as angela merkel
2. go to http://localhost:3000/story/1/1
3. modify the last number in the url to see different story translations
4. attempt to delete translation 
5. observe redirect to homepage
6. attempt to open the last url. observe the 404

## What should reviewers focus on?

- does it work?

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-08 15:36 UTC, gaoxk commented on frontend/src/components/homepage/StoryCard.tsx
> -  const embedLink = (originalYoutubeLink: string): string => {
moved this to Utils.ts

2021-11-10 00:08 UTC, jennifer-lu commented
Very cool!

Not sure if this is expected behaviour, but changing the last number in the url only changes the story translation every two numbers (i.e. http://localhost:3000/story/1/1 and http://localhost:3000/story/1/2 both show East of Eden, http://localhost:3000/story/1/3 and http://localhost:3000/story/1/4 both show War and Peace.

Also, deleting a translation redirects me to http://localhost:3000/404, not the homepage.

2021-11-10 01:22 UTC, gaoxk commented
regarding url changes: thats expected behavior right now. we might migrate away from story/storyid/storytranslationid to story/storytranslationid if the story id proves to be useless

regarding redirect, ill investigate that now!

2021-11-10 01:26 UTC, gaoxk commented
redirect after deleting should work now :)

2021-11-10 03:50 UTC, Puepis commented
> 
> 
> Very cool!
> 
> Not sure if this is expected behaviour, but changing the last number in the url only changes the story translation every two numbers (i.e. http://localhost:3000/story/1/1 and http://localhost:3000/story/1/2 both show East of Eden, http://localhost:3000/story/1/3 and http://localhost:3000/story/1/4 both show War and Peace.
> 
> Also, deleting a translation redirects me to http://localhost:3000/404, not the homepage.

`story/1/1` and `story/1/2` actually show different story translations (two different languages), just under the same story - same with /3 and /4

2021-11-10 04:36 UTC, jennifer-lu commented
> > Very cool!
> > Not sure if this is expected behaviour, but changing the last number in the url only changes the story translation every two numbers (i.e. http://localhost:3000/story/1/1 and http://localhost:3000/story/1/2 both show East of Eden, http://localhost:3000/story/1/3 and http://localhost:3000/story/1/4 both show War and Peace.
> > Also, deleting a translation redirects me to http://localhost:3000/404, not the homepage.
> 
> `story/1/1` and `story/1/2` actually show different story translations (two different languages), just under the same story - same with /3 and /4

I see, thanks for letting me know.

2021-11-10 04:54 UTC, jennifer-lu approved these changes
Looks good to me, everything is working as expected!

2021-11-10 04:54 UTC, jennifer-lu commented on frontend/src/components/pages/ManageStoryTranslationPage.tsx
> +          }}
Nit: for me this box is too tall so the bottom two corners of the iframe are not rounded.

2021-11-11 07:01 UTC, Puepis reviewed
looks good for the most part! just some nits and the embedded video player looks small on my screen, might have something to do with margin/padding/flex

![image](https://user-images.githubusercontent.com/45080644/141252714-31dc0603-2a0f-4a1d-9bdf-b334db94784d.png)

2021-11-13 17:01 UTC, lynn-kim requested changes

2021-11-14 01:56 UTC, gaoxk commented on frontend/src/components/pages/ManageStoryTranslationPage.tsx
> +            colorScheme="red"
![image](https://user-images.githubusercontent.com/15113249/141664471-8487be71-1f1c-4233-9ef4-02da32533b8c.png)
![image](https://user-images.githubusercontent.com/15113249/141664511-7c3acfb5-cb21-4066-a570-d297c2b9f46e.png)

leaving a todo for correcting the way we use the outline variant in a future pr. currently `outline` is explicitly defined in `Button.ts` and is unfortunately blue. removing the explicitly defined `outline` leads to styling regression in the homepage.

2021-11-14 02:16 UTC, gaoxk commented on frontend/src/components/pages/ManageStoryTranslationPage.tsx
> +          <Heading size="sm">Story ID</Heading>
IMO i think this is fine: we're not aligned on most pages with headers 
![image](https://user-images.githubusercontent.com/15113249/141664825-2a455fa2-93e7-477e-8b6a-b5681a82b884.png)

2021-11-14 23:23 UTC, lynn-kim approved these changes

2021-11-14 23:23 UTC, lynn-kim commented on frontend/src/components/pages/ManageStoryTranslationPage.tsx
> +          <Heading size="sm">Story ID</Heading>
sounds good!

2021-11-17 00:28 UTC, merged