Display the correct line number on existing comments
uwblueprint/planet-read pull request #162
Opened 2021-11-17 03:16 UTC by lynn-kim

## Notion ticket link

[Display the correct line number on existing comments](https://www.notion.so/uwblueprintexecs/Display-the-correct-line-number-on-existing-comments-4a8316cf49bd4c6fa8fa488e457f2991)

## Implementation description

- Fetched the line number from the StoryTranslationContent in backend, 
- Renamed some of the props that seem to have changed:
  - commentIndex and WIPCommentIndex refer to the comment number for a specific thread
  - lineIndex is the StoryTranslationContent line number that the comment refers to 
  
<img width="378" alt="Screen Shot 2021-11-16 at 10 14 48 PM" src="https://user-images.githubusercontent.com/37675216/142128085-5e86b372-5a59-467e-a6a2-bae2881f1697.png">

## Steps to test

1. Log in as carl sagan and go to http://localhost:3000/translation/6/13 
2. Check that the comment indices are correct

## What should reviewers focus on?

- Does it work? 
- Does the naming make sense?

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-17 04:39 UTC, gaoxk requested changes
found a bug:
- click big blue comment button
- click comment button by line 2
- make a comment
- save
- existing comment shows up as line 1
- refresh page
- existing comment shows up as line 2 (correct)

2021-11-18 04:54 UTC, lynn-kim commented on frontend/src/APIClients/queries/CommentQueries.ts
> +  lineIndex?: number;
Removed!

2021-11-18 04:56 UTC, lynn-kim commented on frontend/src/components/review/CommentsPanel.tsx
> +              lineIndex={comment.lineIndex || 0}
Fixed here https://github.com/uwblueprint/planet-read/pull/162/commits/45848693a84a6bbe495448dd58cca1129f08f31e

2021-11-18 05:58 UTC, gaoxk approved these changes
noiceee 
just an fyi WIPComment line # is a little funky. going to slot into a different ticket
![image](https://user-images.githubusercontent.com/15113249/142360494-23f00d96-43bf-48bf-98d1-b28d493c731b.png)

2021-11-19 01:50 UTC, merged