Implement level up language flow
uwblueprint/planet-read pull request #222
Opened 2021-12-22 18:03 UTC by gaoxk

## Notion ticket link

[Implement level up language flow](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=ba22ac93d09040ff8219c60ac7caabdb&p=2ca8903a499a4d5bb6b0cb978762d26c)

## Implementation description

- moved the table jsx and specific logic to ApprovedLanguagesTableComponent
- added confirmation modals for leveling up language, and notifying users to move to homepage

## Steps to test

1. login as carl sagan
2. go to user profile 
3. hit level up button 
4. observe that flow exists
5. hit level up button again 
6. observe error `Error: User has an ongoing story translation test for language [abcd].`
7. fail the story translation test to observe the other error.  You'll need to do this in altair as an admin:
```
mutation {
  finishGradingStoryTranslation(storyTranslationTestId: 14, testFeedback: "blah", testResult: "{}"){
    ok
    storyTranslation{
      id
      stage
      
    }
  }
}
```
8. hit level up button again 
9. observe error `Error: User has failed a test within the last 30 days.`
10. hardcode the fail time to be father into the past than 30 days. `UPDATE story_translations SET reviewer_last_activity = '2021-11-01 00:00:00' WHERE id = 14;`
11. hit level up button again. the flow should work and you should be able to make another story test!

## What should reviewers focus on?

- does it work
- does the modularlization of ApprovedLanguagesTableComponent make sense? ApprovedLanguagesTable was getting too cluttered

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-12-22 18:09 UTC, gaoxk commented on backend/python/app/services/implementations/story_service.py
> +                .filter(StoryTranslation.is_test == True)
bug that wasnt caught in a recent pr.

2021-12-22 23:32 UTC, Puepis requested changes
tested and the flow works, just made a comment regarding modal behaviour!

also I missed this in andrew's PR https://github.com/uwblueprint/planet-read/pull/205 but currently the "My Tests" tab shows all of the user's story tests including the ones in REVIEW/PUBLISH stage, i think we should filter those out

2021-12-22 23:32 UTC, Puepis commented on frontend/src/components/admin/ApprovedLanguagesTable.tsx
> +    setAlertNewTest(true);
this causes the second modal to open even when the first one is closed (cancelled)

2021-12-23 02:22 UTC, gaoxk commented
going to log a bug for the 'my test' problem :thumb:

2021-12-23 02:30 UTC, Puepis approved these changes
🚀 🚀 🚀

2021-12-23 02:30 UTC, merged