Make grading page functional
uwblueprint/planet-read pull request #237
Opened 2021-12-23 19:50 UTC by Puepis

## Notion ticket link

https://www.notion.so/uwblueprintexecs/Make-dummy-Test-Grading-platform-functional-4fdb0f5540e14c38acfed93e1d715013

## Implementation description

- allow admin to update story line status to "PENDING" for tests
- redirect to 404 on `/grade` if not a story test
- wrap grading buttons in tooltips to handle story test in TRANSLATE stage
- implement modal for fail user flow (not functional yet)
- modified StatusBadge to accomodate test grading statuses
- keep track of score state in `StoryTestGradingPage.tsx`

## Steps to test

1. `docker exec -it planet-read_py-backend_1 /bin/bash -c "python -m tools.insert_test_data erase"`
2. `docker exec -it planet-read_py-backend_1 /bin/bash -c "python -m tools.insert_test_data"`
3. run `UPDATE story_translations SET stage='REVIEW' WHERE id=13;`
4. create story test using mutation below
5. change status to review using `UPDATE story_translations SET stage='REVIEW' WHERE id=14;`
6. login as admin
7. go to "Manage Tests" and click on "Grade"
8. verify that the action status are PENDING, CORRECT, PARTIALLY_CORRECT, and INCORRECT
9. play around with the status badges, verify that the score updates properly
10. click "Fail User", verify that the modal shows up (not functional yet)

#### Check review page
1. login as `planetread+dwightdeisenhower@uwblueprint.org`
2. click "View Translation" on "The Great Gatsby"
3. verify that the review platform works as normal, especially the action statuses

#### Create story test
```
mutation CreateStoryTest {
  createStoryTranslationTest(userId: 4, level:2, language:"FRENCH"){
    story{
      id
      translatorId
      storyId
      language
      stage
    }
  }
}
```

#### 

## What should reviewers focus on?

- does it work?
- is the styling okay?

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-12-23 20:37 UTC, gaoxk requested changes
![image](https://user-images.githubusercontent.com/15113249/147289513-49092439-46ed-43d6-8ae7-dc3e05b3d1af.png)
everything worked when testing! only thing is that the padding is non existent now, mind keeping it in?

2021-12-23 20:37 UTC, gaoxk commented on frontend/src/components/pages/StoryTestGradingPage.tsx
> +    const newScore = translatedStoryLines.reduce(scoreReducer, 0);
niceeeeeeeee i luv reducers 😎

2021-12-23 20:37 UTC, gaoxk commented on frontend/src/components/pages/StoryTestGradingPage.tsx
> +        console.log(data);
nit: remove consolelog

2021-12-23 20:37 UTC, gaoxk commented on frontend/src/components/review/StatusBadge.tsx
> +const REVIEW_STATUS_OPTIONS: StatusOption[] = [
noiceee i like the StatusOption lists

2021-12-23 23:31 UTC, Puepis commented
> only thing is that the padding is non existent now, mind keeping it in?

oops mb will revert

2021-12-24 00:54 UTC, gaoxk requested changes
hmmm it looks good on the grading platform but padding is still missing from translation platform:
![image](https://user-images.githubusercontent.com/15113249/147302944-ec6b403f-e6f0-4892-a353-a22552e5fb1f.png)
and review platform:
![image](https://user-images.githubusercontent.com/15113249/147302971-cf5f5a39-1a87-4a1e-94a0-c597a2b5018c.png)

seems that the badges on the homepage story cards are really tight too now 
![image](https://user-images.githubusercontent.com/15113249/147302987-19c131bc-b8a6-4fa1-9725-eee96626727e.png)
maybe the styling problem isnt from the ApproveAll component but the StatusBadges?

2021-12-24 03:02 UTC, Puepis commented
i think styling should be fixed now! 🙏
![grading](https://user-images.githubusercontent.com/45080644/147310762-0355538c-3be9-4a48-b00d-cedbb37f4698.PNG)
![homepage](https://user-images.githubusercontent.com/45080644/147310769-588cd65e-f6be-413f-aba9-c9416b99bc25.PNG)
![pending](https://user-images.githubusercontent.com/45080644/147310778-3ddd5bbd-7373-4b2f-a98d-b05b64edaec8.PNG)

2021-12-24 03:14 UTC, gaoxk approved these changes
NOICE

2021-12-24 03:14 UTC, merged