Make import story page functional
uwblueprint/planet-read pull request #327
Opened 2022-01-10 20:42 UTC by lynn-kim

## Notion ticket link

[Make import story page functional](https://www.notion.so/uwblueprintexecs/Make-import-story-page-functional-1efdd94431684af68a257d71e98c9ed1)

## Implementation description

- Added functionality to import story page
- Also slipped a very small change to use Noto for headings 

## Steps to test

1. Log in as angela
2. Go to http://localhost:3000/#/story/15
3. Try uploading a story 
4. Check that it works! 
5. Check that you are redirected to the story page

## What should reviewers focus on?

- Does it work?

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-11 00:34 UTC, gaoxk requested changes
Nuceee fyi the preview modal needs to be implemented but I split up the ticket since I think the scope of this pr is fine

2022-01-11 00:34 UTC, gaoxk commented on frontend/src/components/pages/ImportStoryPage.tsx
> +          level,
Can you add the excluded languages as translated_languages in this call? Currently the column is null

2022-01-12 15:11 UTC, lynn-kim commented
@jennifer-lu did that go to the wrong branch?

2022-01-12 15:11 UTC, jennifer-lu commented
> @jennifer-lu did that go to the wrong branch?

Yes sorry!

2022-01-12 15:19 UTC, jennifer-lu commented
@lynn-kim Should be fixed now, does it look ok?

2022-01-12 15:51 UTC, gaoxk approved these changes
noice

2022-01-12 16:32 UTC, merged