Backend/seed database script
uwblueprint/planet-read pull request #38
Opened 2021-06-28 21:45 UTC by andrewyguo

## Notion ticket link

[Seed Database](https://www.notion.so/uwblueprintexecs/Write-script-to-seed-database-b8f9b72b2f9e4f64ac45258e4e63d884)

## Implementation description
* Create shell script to seed the users, stories, and story_translations data bases  
* Also has option to clear the three data bases 

## Steps to test
1. Go into the root directory of `planet-read` and run `./seed_db.sh erase`
2. Set the variables `ADMIN_AUTH_ID` and `USER_AUTH_ID` to their respective values (can be found in the **planetread-secrets** channel) 
3. After data base has been cleared, run `./seed_db.sh` 

## What should reviewers focus on?
* That the script successfully generates 7 entries for `users`, 7 entries for `stories`, and 21 entries for `story_translations `

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters:  `docker exec -it <backend-container-id> /bin/bash -c "black . && isort --profile black ."`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-06-30 00:52 UTC, gaoxk requested changes
lookin good 😎  can you send a message to the dev slack channel about the CRLF vs LF issue we ran into? Seems like some folks will have to switch the file ending type to make it work.

2021-06-30 00:52 UTC, gaoxk commented on seed_db.sh
> +    docker exec -it planet-read_db_1 psql -U postgres -d planet-read -c "INSERT INTO stories (title, description, youtube_link, level, translated_languages) VALUES ('Kevin Burns Coal to Create Smog',
Can you use real youtube links? That way the story cards load real youtube iframes. Feel free to use random youtube videos.

2021-06-30 00:52 UTC, gaoxk commented on seed_db.sh
> +    docker exec -it planet-read_db_1 psql -U postgres -d planet-read -c "INSERT INTO users (first_name, last_name, auth_id, role, approved_languages) VALUES ('Angela', 'Merkel', '$ADMIN_AUTH_ID', 'Ad
Let's keep all possible levels between 1 and 4

2021-06-30 00:52 UTC, gaoxk commented on seed_db.sh
> +if [ -z "$ADMIN_AUTH_ID" ]
i think the script should exit if these AUTH_IDs are missing, unless the `erase` command is being passed in.

2021-06-30 00:52 UTC, gaoxk commented on seed_db.sh
> +# In the directory of the script, call ./seed_db.sh [OPTION]
nit: Just to make things crystal clear, can you add an example like

`USER_AUTH_ID=123 ADMIN_AUTH_ID=1234 ./seed_db.sh kevin`

2021-06-30 01:26 UTC, gaoxk commented
Discussion from the discord conversation:
- make new firebase users with easy to remember passwords/emails (eg planetread+angelamerkel@uw..)
- once this pr is merged, send message to secrets channel of 
  - generated user email & passwords
  - all environment variables set on one line to make copy paste ezpz for developers
- make sure inserted `story_translations` line up with their respectiove `story.translated_languages`

2021-07-03 00:09 UTC, gaoxk requested changes
Looks good! lets merge after two small nits :)

2021-07-03 00:29 UTC, gaoxk commented
one more thing: can you insert some `story_content `+ respective `story_translation_content `for each of the stories and story translations? feel free to make a loop making incoherent garbage text to keep the script concise.

2021-07-03 22:37 UTC, e-wai commented on seed_db.sh
> +        docker exec -it planet-read_db_1 psql -U postgres -d planet-read -c "INSERT INTO story_contents (story_id, line_index, content) VALUES ('$STORY_ID', 1, '“Every two weeks I went to a meeting w
Hey, I'm using some of the script manually atm: 

` ('$STORY_ID', 1, '“Every ` -> what's the `“` for?

2021-07-04 23:21 UTC, gaoxk requested changes

2021-07-04 23:21 UTC, gaoxk commented on seed_db.sh
> +    for STORY_TRANSLATION_ID in 2 3 5 7 11 13
For every story_translation that exists, the respective story_translation_content lines must also exist (see [create_story_translation](https://github.com/uwblueprint/planet-read/blob/main/backend/python/app/services/implementations/story_service.py#L85) service). i.e. if you create a story translation of a 6 line story, the there must also be 6 lines of story translation content created with  empty strings. 

A quick fix is to run this forloop from 1 to 13. To diversify our data, you can make one story translation full of emtpy strings, and one that has some empty and some full lines.

2021-07-07 01:35 UTC, gaoxk requested changes

2021-07-07 01:35 UTC, gaoxk commented on seed_db.sh
> +        docker exec -it planet-read_db_1 psql -U postgres -d planet-read -c "INSERT INTO story_translation_contents (story_translation_id, line_index, translation_content) VALUES ('$STORY_TRANSLATION
nit: you can nest a `for i in 1 2 3 4 5 6 7 8 9 10` and use `i` as the `line_index` here to reduce the repeat code.

2021-07-07 01:35 UTC, gaoxk commented on seed_db.sh
> +        docker exec -it planet-read_db_1 psql -U postgres -d planet-read -c "INSERT INTO story_translation_contents (story_translation_id, line_index, translation_content) VALUES ('$STORY_TRANSLATION
ditto nit

2021-07-07 01:46 UTC, gaoxk approved these changes

2021-07-07 01:46 UTC, merged