Add is_reviewer and get_user_id_from_request
uwblueprint/planet-read pull request #95
Opened 2021-09-15 02:41 UTC by gaoxk

## Implementation description

- added `get_user_id_from_request `utility to middlewares.auth.py
- added `is_reviewer `to auth service

## Steps to test
`get_user_id_from_request `
You're gunna have to trust me on this one, LOL. Here's how to use it in a service:
![image](https://user-images.githubusercontent.com/15113249/133361246-96fefc1f-8873-4396-b6ca-7093618287f5.png)
opening the homepage and browsing stories as translator would cause the user id to be printed. 

is_reviewer 
This is essentially the same code as is_translator. To test, go to translation page and type some stuff. The translation should be successfully updated, ie refreshing the page will keep the changes made.

## What should reviewers focus on?

- clarity

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-09-15 02:53 UTC, gaoxk commented
jk... dont need to import and pass request.
![image](https://user-images.githubusercontent.com/15113249/133362601-ecf70273-d0f6-4c19-9b40-b4285eeaf725.png)

2021-09-16 00:26 UTC, jennifer-lu approved these changes
LGTM!

2021-09-16 00:29 UTC, Puepis requested changes
The `is_reviewer` function looks good, just left some comments for minor tweaks!

2021-09-16 04:39 UTC, Puepis approved these changes
LGTM!

2021-09-16 13:50 UTC, merged