Create Existing comment component
uwblueprint/planet-read pull request #97
Opened 2021-09-15 03:46 UTC by ArmanyaDalmia

## Notion ticket link

[Create existing comment component](https://www.notion.so/uwblueprintexecs/a658c933d18c48d4b43fd99bda2bd3b4?v=4a47edc475b34bb99b25ff1fae2a5507&p=db62b18f0f9f4422a833567c45883520)

## Implementation description

- Created gql mutation fou updating user
- Created Existing comment component

## Steps to test

1. Add component to TranslationPage (making sure comment being displayed is not resolved)
2. Confirm pressing reply opens a WIP comment component
3. Confirm pressing respond updates the resolved value for the comment in the db

## What should reviewers focus on?

- That the functionality is as desired (still need to add styling)

## Checklist

- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] For backend changes, I have run the appropriate linters: `docker exec -it planet-read_py-backend_1 /bin/bash -c "black . && isort --profile black ."` and I have generated new migrations: `flask db migrate -m "<your message>"`
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-09-17 20:24 UTC, gaoxk requested changes
drive by review!

2021-09-17 20:24 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +export type ExistingCommentProps = {
dont forget about displaying the time! 
![image](https://user-images.githubusercontent.com/15113249/133848772-96f1ea53-77d7-4565-935d-e8394e801eee.png)

2021-09-17 20:24 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +        <Button onClick={() => setReply(true)}>Reply</Button>
some thoughts about styling (that you might already be implementing): you'll want to add a new button variant in chakra ui for styling the Reply and Resolve buttons (eg theme/components/Button.ts)

2021-09-17 20:24 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +      {reply === true && (
nit: i think you can simplify to `{reply && (`

2021-09-23 16:06 UTC, gaoxk requested changes
It's coming along! Btw, I don't mind if you include the code use of the ExistingComment component in the comments panel. Makes it easier for me to test too lmao

2021-09-23 16:06 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +        <p>{time}</p>
fyi: comments panel is not fetching time right now in `CommentsQueries.ts`
```
const COMMENT_FIELDS = `
    id
    commentIndex
    content
    storyTranslationContentId
    `;
```
Are you testing this component by like so in the comments panel?
```
const CommentsList = () => {
         ....
          <ExistingComment
              key={comment.id}
              id={comment.id}
              resolved={comment.resolved}
              content={comment.content}
              time={comment.time}
              commentStoryTranslationContentId={
                commentStoryTranslationContentId
              }
              setCommentLine={setCommentLine}
              lineIndex={comment.commentIndex}
            />
          ))}
```
comments panel looks like this for me rn (time is missing)
![image](https://user-images.githubusercontent.com/15113249/134542852-057f8812-b3ba-40e7-a0dd-c1179c2800cf.png)
Based on the mocks, the time should also be on the same line as the name. Feel free to wrap these two in a `Flex` and `justifyContent: space-between` or something along those lines

2021-09-23 16:06 UTC, gaoxk commented on frontend/src/theme/components/Button.ts
> +    text: {
hmmm maybe a better name is `label` as it's called on figma?

2021-09-23 16:09 UTC, gaoxk commented
one more fyi - the reply button did nothing for me when I used the `ExistingComment` component in the `CommentPanel`

2021-10-20 03:09 UTC, gaoxk requested changes

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/theme/components/Button.ts
> +    label: {
nit: sort these attributes alphabetically

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +      {reply > 0 && lineIndex > -1 && (
when is `lineIndex == -1`?

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +      border="1px solid"
nit: alphabetize these props

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +      style={{
why is the `style` prop needed? Can `borderRadius` and `width` be set as a usual chakra ui prop?

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/theme/components/Button.ts
> +    label: {
nit: `label` is a bit of a vague line, what about `commentLabel`

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +        const result = await updateComment({
Nothing is being done with this result (getting a build error for it)

2021-10-20 03:09 UTC, gaoxk commented on frontend/src/components/review/ExistingComment.tsx
> +  const [reply, setReply] = useState(0);
I'm trying to wrap my head around `reply` and `commentLine`: are you treating `reply` as a boolean/flag for displaying a `WIPComment`?

2021-11-03 03:44 UTC, gaoxk commented
The comment button seems to always be disabled for me 
![image](https://user-images.githubusercontent.com/15113249/140007340-8588fa33-5c8f-4dde-9d79-0fa08bf43546.png)

2021-11-04 15:26 UTC, ArmanyaDalmia commented
> The comment button seems to always be disabled for me ![image](https://user-images.githubusercontent.com/15113249/140007340-8588fa33-5c8f-4dde-9d79-0fa08bf43546.png)

![image](https://user-images.githubusercontent.com/32991028/140352458-b39508b4-156d-4d7f-b095-05123870ec5c.png)
I'm able to reply to the comment, so I have no idea why the button is disabled for you

2021-11-04 19:38 UTC, gaoxk commented
Tested it again and this seems to be the core issue:
1. click reply
2. enter text into the WIPComment component and hit comment
3. get the following error
![image](https://user-images.githubusercontent.com/15113249/140408214-8c6bdb6f-571a-4193-bd19-c465399acc6e.png)
this is the network response from the createComment mutation:
```
{"errors":[{"message":"'NoneType' object has no attribute 'stage'","locations":[{"line":2,"column":3}],"path":["createComment"]}],"data":{"createComment":null}}
```
4. I run into disabling issues after that

2021-11-05 02:26 UTC, gaoxk approved these changes
🚢 🚢 🚢 🚢

2021-11-06 07:27 UTC, merged